### ISSUE TITLE
conflict with redmine_status_history in css

### ISSUE THREAD

**Issue by ashrafalzyoud** [sk-ys/redmine_enhanced_ux#20]
https://github.com/redmineservices/redmine_status_history

![search status history](https://github.com/user-attachments/assets/63b70a82-c2bd-4f6e-a757-9c83b5960b21)

plz solve it

**Comment by ashrafalzyoud** [comment]
@sk-ys

**Comment by sk-ys** [comment]
@ashrafalzyoud
I have never used this plugin. How to use this plugin?

**Comment by sk-ys** [comment]
> @ashrafalzyoud I have never used this plugin. How to use this plugin?

I have confirmed that the link is at the bottom of the issue list.

**Comment by sk-ys** [comment]
@ashrafalzyoud
I redesigned the issue list page. Please check it.
https://github.com/sk-ys/redmine_enhanced_ux/tree/issue-20

**Comment by sk-ys** [comment]
@ashrafalzyoud 
Can I close this issue?

**Comment by ashrafalzyoud** [comment]
thx for your solution
